---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
  run_list: ["recipe[apt]"]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    require_chef_omnibus: true
  run_list: ["recipe[apt]"]
- name: debian-7
  driver_config:
    box: opscode-debian-7
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-7.0.0_provisionerless.box
    require_chef_omnibus: true
  run_list: ["recipe[apt]"]
- name: debian-6
  driver_config:
    box: opscode-debian-6
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_chef-11.2.0.box
    require_chef_omnibus: true
  run_list: ["recipe[apt]"]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: true

suites:
- name: openjdk
  run_list: ["recipe[minitest-handler]", "recipe[java::openjdk]"]
  attributes: {}

- name: oracle
  run_list: ["recipe[minitest-handler]", "recipe[java::oracle]"]
  attributes:
    java:
      oracle:
        accept_oracle_download_terms: true
      install_flavor: "oracle"
